# Machine Learning Zoomcamp

## 1.7 Introduction to Numpy

##### Plan:
* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [5]:
import numpy as np

In [6]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

1 dimensional arrays

In [4]:
# Creating Arrays
np.zeros(5)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [10]:
a = np.array([1,2,3,4,5,7,12])

In [12]:
a[2] = 10

In [13]:
a

array([ 1,  2, 10,  4,  5,  7, 12])

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [17]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

# Multi-dimensional arrays

In [18]:
np.zeros((5,2)) #5 rows 2 Columns

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:

n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [23]:
# Access elements of an array
#n[r,c]
n[0,1] = 20
n


array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [24]:
# Assess things by row
n[1]

array([4, 5, 6])

In [26]:
n[2] = [1,1,1] # changes the column

In [27]:
n 

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [28]:
# Access a Column
# Get all rows in column 1
n[:, 1]

array([20,  5,  1])

In [29]:
n[:] # returns all the rows

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [32]:
n[:,2] = [0,1,2] # changes the last row
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

# Randomly Generated Arrays

In [35]:
np.random.seed(2) # makes the result reproducable, the same on different computers
np.random.rand(5,2) # numbers btw 0 and 1

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [37]:
np.random.seed(2) # makes the result reproducable, the same on different computers
np.random.randn(5,2) #- random normal dist

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [38]:
np.random.seed(2) # makes the result reproducable, the same on different computers
100 * np.random.rand(5,2) # numbers btw 0 and 100

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [39]:
np.random.seed(2) # makes the result reproducable, the same on different computers
np.random.randint(low=0, high= 100, size = (5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise operations

In [40]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [43]:
# Addition
b = (10 + (a * 2)) ** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [44]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [45]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

# Comparison Operations

In [46]:
a

array([0, 1, 2, 3, 4])

In [47]:
a >= 2

array([False, False,  True,  True,  True])

In [48]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [49]:
a > b

array([False, False,  True,  True,  True])

In [50]:
a[a > b]

array([2, 3, 4])

# Summarizing Operations

In [51]:
a

array([0, 1, 2, 3, 4])

In [52]:
a.max()

np.int64(4)

In [53]:
a.sum()

np.int64(10)

In [54]:
a.mean()

np.float64(2.0)

In [55]:
a.std()

np.float64(1.4142135623730951)

In [56]:
n.sum()

np.int64(35)